# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - anyu-ui

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    environment: Production
    defaults:
      run:
        working-directory: anyu-ui

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Replace environment placeholders
        run: |
          $envFile = "src/environments/environment.prod.ts"
          $content = Get-Content $envFile -Raw
          $content = $content -replace "#\{EnvironmentName\}#", "${{ env.ENVIRONMENT_NAME }}"
          $content = $content -replace "#\{AuthRedirectUri\}#", "${{ env.AUTH_REDIRECT_URI }}"
          $content = $content -replace "#\{ApiUrl\}#", "${{ env.API_URL }}"
          $content = $content -replace "#\{UiUrl\}#", "${{ env.UI_URL }}"
          Set-Content $envFile -Value $content
        env:
          ENVIRONMENT_NAME: ${{ env.ENVIRONMENT_NAME }}
          AUTH_REDIRECT_URI: ${{ env.AUTH_REDIRECT_URI }}
          API_URL: ${{ env.API_URL }}
          UI_URL: ${{ env.UI_URL }}

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          # npm run test --if-present

      - name: Create Archive of Build Output
        run: |
          Compress-Archive -Path dist/anyu-ui/* -DestinationPath ../build.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: build.zip

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip build artifact
        run: |
          Expand-Archive -Path build.zip -DestinationPath . -Force

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'anyu-ui'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2DDD94E853A9409485FCF0E0420B4FF5 }}
          package: .
